### ISSUE TITLE
[Help wanted] Real-time speech recognition from a microphone

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/sherpa-onnx#34]
# TODO (Python)
- [x] Follow https://github.com/k2-fsa/sherpa-ncnn/blob/master/python-api-examples/speech-recognition-from-microphone.py
       support microphone in Python (fixed in #46)

# TODO( C++)

- [x] Follow https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/sherpa-ncnn-microphone.cc to support PortAudio
- [x] Follow https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/sherpa-ncnn-alsa.cc to support ALSA

**Comment by csukuangfj** [comment]
Closing as it is finished.
